### ISSUE TITLE
sbt-scrooge deprecated in favor of scrooge/scrooge-sbt-plugin

### ISSUE THREAD

**Issue by MasseGuillaume** [twitter/sbt-scrooge#11]
Is it possible to update the readme to point to the newest plugin ?

The artifact is on sonatype: https://oss.sonatype.org/content/groups/public/com/twitter/scrooge-sbt-plugin_2.10_0.13/3.13.2/
The repo is here: https://github.com/twitter/scrooge/tree/master/scrooge-sbt-plugin

**Comment by grimreaper** [comment]
Thank you for your contribution! Twitter has decided to stop supporting sbt-scrooge as an open source project. Sorry that your issue was not reviewed earlier.
We're now formally archiving this project but please feel free to fork and resurrect.
